name: geosteering
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  # Jupyter Notebook
  - jupyter
  - ipykernel
  # Data Science ML
  - pandas
  - numpy<2.0.0
  - scikit-learn
  # Visualization
  - matplotlib
  - seaborn
  - tqdm
  # GPU Support
  - pip:
      - --index-url https://download.pytorch.org/whl/cu130
      - torch
      - torchvision
      - torchaudio